services:
  database:
    image: postgres:17
    container_name: bmv-database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bmv
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d bmv"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - bmv-network
    
networks:
  bmv-network:
    driver: bridge

volumes:
  database: